backend:
  name: git-gateway
  branch: main
media_folder: public/images
site_url: https://luis-schwamm.weinstock.it
display_url: luisschwamm.de
logo_url: /images/Profilbild.png # Logo used in CMS
public_folder: /images
# publish_mode: editorial_workflow
locale: 'de'
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: 'config'
    label: 'Einstellungen'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Website Einstellungen'
        file: 'config.json'
        description: 'General site settings'
        fields:
          - label: 'URL'
            name: 'base_url'
            widget: 'string'
            hint: 'Do not enter the trailing slash of the URL'
          - label: 'Site title'
            name: 'site_title'
            widget: 'string'
          - label: 'Site description'
            name: 'site_description'
            widget: 'string'
          - label: 'Site keywords'
            name: 'site_keywords'
            widget: 'list'
            summary: '{{fields.keyword.keyword}}'
            field:
              label: Keyword
              name: keyword
              widget: 'string'
          # - label: 'Twitter account'
          #   name: 'twitter_account'
          #   widget: 'string'
          - label: 'GitHub account'
            name: 'github_account'
            widget: 'string'
      - name: 'authors'
        label: 'Authors'
        file: 'meta/authors.yml'
        description: 'Author descriptions'
        fields:
          - name: authors
            label: Authors
            label_singular: 'Author'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the author'
              - label: 'Name'
                name: 'name'
                widget: 'string'
                hint: 'First and Last'
              - label: 'Introduction'
                name: 'introduction'
                widget: 'text'
          - name: 'tags'
            label: 'Tags'
            file: 'meta/tags.yml'
            description: 'List of tags'
            fields:
              - name: tags
                label: Tags
                label_singular: 'Tag'
                widget: list
                fields:
                  - label: 'Slug'
                    name: 'slug'
                    widget: 'string'
                    hint: 'The part of a URL identifies the tag'
                  - label: 'Display Name'
                    name: 'name'
                    widget: 'string'
                    hint: 'Tag name for displaying on the site'

  - name: 'pages'
    label: 'Seiten'
    delete: false
    editor:
      preview: false
    files:
      - name: 'social'
        label: '[Unterseite] Soziales'
        file: 'meta/social.yml'
        description: 'Social Section on Page'
        fields:
          - name: title
            label: Titel
            widget: 'string'
          - name: bandcamp
            label: Bandcamp
            widget: 'string'
          - name: spotify
            label: Spotify
            widget: 'string'
          - name: youtube
            label: YouTube
            widget: 'string'
          - name: soundcloud
            label: SoundCloud
            widget: 'string'
          - name: insta
            label: Instagram
            widget: 'string'
          - name: facebook
            label: Facebook
            widget: 'string'

  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts/'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        dateFormat: 'YYYY-MM-DD'
        timeFormat: false
      - label: Author
        name: 'author'
        widget: relation
        collection: 'meta'
        file: 'authors'
        searchFields:
          - 'authors.*.name'
        displayFields:
          - 'authors.*.name'
        valueField: 'authors.*.slug'
      - label: Tags
        label_singular: 'Tag'
        name: 'tags'
        widget: list
        summary: '{{fields.tag}}'
        field:
          label: Tag
          name: tag
          widget: relation
          collection: 'meta'
          file: 'tags'
          searchFields:
            - 'tags.*.name'
          displayFields:
            - 'tags.*.name'
          valueField: 'tags.*.slug'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
