#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# checks if everyone uses prettier
npx prettier -l --write . 
# linting and adding the fixed files before comitting
yarn eslint --ext .tsx,.ts . --fix && git add -A .
